DROP TABLE IF EXISTS guestList;


CREATE TABLE guestList (
    id SERIAL PRIMARY KEY,
    guest TEXT,
    email TEXT,
    response TEXT DEFAULT '',
    CONSTRAINT valid_response CHECK (response IN ('', 'accept', 'decline'))
);


INSERT INTO guestlist (guest) VALUES
('Melny Ibarra'),
('Aeron Jake Daelo'),
('Imelda Ibarra'),
('Danilo Ibarra'),
('Angelina Daelo'),
('Arnaldo Daelo'),
('Ellah Ibarra'),
('Andrea Reambonanza'),
('Shella Mae Gingo'),
('Marrion Mae Sison'),
('Kristine Arsenio'),
('Katrina Cana'),
('Eliza Mae Sanclaria'),
('Louie Armand Tabelisma'),
('Rejune Buensuceso'),
('Lazaro Campanero'),
('John Curt Pascual'),
('Danilo Ibarra Jr'),
('Khristian Paul Pimentel'),
('Erwin Jan Evaristo'),
('Marilyn Alpuerto'),
('Jovie Alpuerto'),
('Shirley Arcangel'),
('Allan Arcangel'),
('Jelma Celeste'),
('Rogelio Celeste'),
('Constancia Lumata'),
('Joel Lumata'),
('Karen Daelo'),
('Maricon Daelo'),
('Judith Espinosa'),
('Joel Espinosa'),
('Marcelina Evaristo'),
('Hermogenes Evaristo'),
('Eulalia Gingo'),
('Daniel Gingo'),
('Leonor Reambonanza'),
('Esterlita Reambonanza'),
('Alejandro Ibarra'),
('Mi-Ann Penalosa'),
('Jeffrey Penalosa'),
('Jerickson Tino'),
('Race Arbie Rimando'),
('Jefferson Tino'),
('Samantha Arcangel'),
('Hannah Venice Bucsit'),
('Antonette Grace Daelo-Cardona'),
('Aron Paul Cardona'),
('Amparo Ibarra'),
('Emerita Verana'),
('Teodora Pagulong'),
('Karen Pagulong'),
('Remedios Sumarzar'),
('Florante Sumarzar'),
('Junbert Yangco'),
('Angelyn Yangco'),
('Andres Reambonanza'),
('Nene Reambonanza'),
('Kenneth Reambonanza'),
('Andrew Reambonanza'),
('AJ Elison'),
('Daisy Tenorio'),
('Loraine Celino'),
('Justine Alpuerto'),
('Jovene Alpuerto'),
('Alexcess Neil Ibarra'),
('Kyle Ibarra'),
('Frederick Palileo'),
('Ryan Francis Penaflor'),
('Sophia Yvonne Mendoza'),
('John Paul De la Cruz'),
('Jayrell Dioquino'),
('Neil Eiberson Tino'),
('Nelson Tino'),
('Gabriel Arcangel'),
('Kyrie Daelo'),
('Khallyl Dylan Daelo'),
('Kenzo Daelo'),
('Loujie Aquino'),
('Eunice Gladys Ann Urquhart'),
('Jasmine Espinosa'),
('Joshua Espinosa'),
('Ernesto Bucsit'),
('Eufemia Bucsit'),
('Jason Bucsit'),
('Rovelyn Bucsit'),
('Rodel Bucsit'),
('Belinda Bucsit'),
('Andres Deocareza'),
('Ryan Sumarzar'),
('Mike Dalagan'),
('Bryan Kent Daelo'),
('Allen Daelo'),
('Lorie Daelo'),
('Leila Daelo'),
('Lenlen Daelo'),
('Kharllo Pernetes'),
('Julie Ann Pernetes'),
('Maristel Madelo'),
('Kian Madelo'),
('Janred Madelo'),
('Erick Cloyd Cerda'),
('Arke-JR Daguio'),
('Caroleen Petate'),
('Marevick De Jesus'),
('Jovene Codinera'),
('Zarah Bandal'),
('Jarome Albutra'),
('Roland Reuben Avendano'),
('Ana Rebuya'),
('Sara Teus'),
('Patrick Dominguez');


UPDATE guestList
SET response = 'accept'  -- new response
WHERE guest = 'Melny Ibarra' AND email = 'melny@example.com';
